### ISSUE TITLE
/paypal_return/ is 1 line of text

### ISSUE THREAD

**Issue by Planks** [esamarathon/donation-tracker#10]
Can we make it more hype, like showing how your donation impacted on your chosen goal?

At least give it a nice stylesheet, the new donation total, and a link back to the main tracker page

And some text, something like this?
"Thanks for your donation! Every cent goes directly to Save the Children and contributes to their global cause. Your donation comment will be reviewed by ESA crew and potentially selected for reading on stream."

**Comment by zephyyrr** [comment]
How about this: 
https://donations.esamarathon.com/paypal_return/

**Comment by Planks** [comment]
Nice big save the children logo might round it off

@zoton2 has assets
