### ISSUE TITLE
Editing a prize to include start and end run caused prizes section to crash

### ISSUE THREAD

**Issue by Planks** [esamarathon/donation-tracker#11]
As title

**Comment by zephyyrr** [comment]
Problem is because runs are not assigned a start and end time.
This cases error all over the code and I have been patching them individually since I reasoned we did not need this in the tracker anyway.

Unfortunately, since prizes are linked to donation timestamp, I actually need to fix this now.

**Comment by zephyyrr** [comment]
Fixed by importing runs from Horaro with proper start times.
