### ISSUE TITLE
Require donate link

### ISSUE THREAD

**Issue by Planks** [esamarathon/donation-tracker#8]
The splash page, https://donations.esamarathon.com/, does not have a donate link

**Comment by zephyyrr** [comment]
That is because an event needs to be selected for it to know which event to donate towards.
I think it will automatically take you to the active event if there is one. I'll get back to you after checking there indeed is such a feature.

**Comment by zephyyrr** [comment]
No such feature, but easily fixed.
I'll just make if try to get the latest event from the DB if one is not already specified.

It is not perfect, but I can work on a function to grab the "active" event after Winter.
